import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Fake API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ fontFamily: "sans-serif" }}>
        <h1>Hello</h1>
        <p>This is a Next app with a fake API.</p>

        <h2>Users API</h2>
        <nav style={{ marginTop: "10px", display: "flex", flexDirection: "column", gap: "10px" }}>
          <StyledLink href="/api/users" label="Users" />
          <StyledLink href="/api/users/1" label="User By ID" />
          <StyledLink href="/api/users/random" label="Random User" />
        </nav>

        <h2>Todos API</h2>
        <nav style={{ marginTop: "10px", display: "flex", flexDirection: "column", gap: "10px" }}>
          <StyledLink href="/api/todos" label="Todos" />
          <StyledLink href="/api/todos/9cba" label="Todo By ID" />
          <StyledLink href="/api/todos/random" label="Random Todo" />
        </nav>
      </div>
    </>
  );
}

function StyledLink({ href, label }: { href: string; label: string }) {
  return (
    <>
      <Link href={href} className="link" target="_blank">
        {label}
      </Link>

      <style>
        {`
          .link {
            padding: 12px;
            text-decoration: none;
            background: #eee;
            color: #333;
          }
          .link:hover {
            background: #ddd;
          }
       `}
      </style>
    </>
  );
}
