import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Fake API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello</h1>
        <p>This is a Next app with a fake API.</p>

        <nav style={{ marginTop: "10px", display: "flex", flexDirection: "column", gap: "10px" }}>
          <StyledLink href="/api/users" label="Users" />
          <StyledLink href="/api/users/1" label="User [id]" />
          <StyledLink href="/api/users/random" label="Random User" />
        </nav>
      </div>
    </>
  );
}

function StyledLink({ href, label }: { href: string; label: string }) {
  return (
    <>
      <Link href={href} className="link" target="_blank">
        {label}
      </Link>

      <style>
        {`
          .link {
            background: #ddd;
            padding: 10px;
          }
          .link:hover {
            background: #ccc;
          }
       `}
      </style>
    </>
  );
}
